extends:
  - '@meyfa/eslint-config'
  - '@meyfa/eslint-config/jsdoc'
  - 'plugin:vue/recommended'

overrides:
  - files: ['*.ts', '*.vue']
    parser: vue-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions: ['.vue']
      project: './tsconfig.lint.json'

rules:
  vue/html-indent: ['error', 2, { attribute: 2, baseIndent: 1, closeBracket: 0, alignAttributesVertically: false }]
  vue/max-attributes-per-line: 0
  vue/singleline-html-element-content-newline: 0
  vue/html-closing-bracket-newline: 0
  vue/component-name-in-template-casing: [2, PascalCase]
