extends:
  - standard-with-typescript
  - plugin:jsdoc/recommended
  - plugin:vue/recommended

overrides:
  - files: ['*.ts', '*.vue']
    parser: vue-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions: ['.vue']
      project: './tsconfig.json'

globals:
  API_ENDPOINT: readonly
  PRIVACY_POLICY_URL: readonly

rules:
  vue/html-indent: ['error', 2, { attribute: 2, baseIndent: 1, closeBracket: 0, alignAttributesVertically: false }]
  vue/max-attributes-per-line: 0
  vue/singleline-html-element-content-newline: 0
  vue/html-closing-bracket-newline: 0
  vue/component-name-in-template-casing: [2, PascalCase]
  # require JSDoc on every standard location, and also on classes, interfaces and enums
  jsdoc/require-jsdoc: ['error', { contexts: [ 'ClassDeclaration', 'TSInterfaceDeclaration', 'TSEnumDeclaration' ] }]
  jsdoc/require-param-type: off
  jsdoc/require-returns-type: off
  jsdoc/no-types: error
