extends:
  - plugin:vue/recommended

globals:
  process: readonly
  API_ENDPOINT: readonly
  PRIVACY_POLICY_URL: readonly

rules:
  vue/html-indent: ["error", 2, { attribute: 2, baseIndent: 1, closeBracket: 0, alignAttributesVertically: false }]
  vue/max-attributes-per-line: 0
  vue/singleline-html-element-content-newline: 0
  vue/html-closing-bracket-newline: 0
  vue/html-self-closing: [2, { html: { void: always, normal: never, component: never } }]
  vue/component-name-in-template-casing: [2, kebab-case]
